/**
 * Implementation of `stxt describe <file|->`.
 *
 * This command deliberately parses only the base STXT grammar. A canonical tree describes the
 * parser result defined by STXT-TREE-SPEC; schema discovery and validation are a separate layer
 * and belong to `stxt validate`. On success, stdout contains precisely one canonical JSON document
 * generated by the public API of `@stxt-lang/core`. `-` reads the document from the standard
 * input, reported as `<stdin>` in the diagnostics.
 */

import * as path from "path";
import { Parser, toCanonicalJson } from "@stxt-lang/core";
import { CliIO } from "../runtime/Cli";
import { ExitCode } from "../runtime/ExitCode";
import { DocumentSource, fileSource, readStdin, STDIN_NAME, STDIN_TARGET } from "../runtime/StxtFiles";

/** Dependencies {@link runDescribe} needs beyond argument parsing. */
export interface DescribeDependencies {
    /** Working directory relative paths are resolved against. Defaults to `process.cwd()`. */
    cwd?: string;

    /** How `-` reads the standard input. Defaults to reading the real one. */
    readStdin?: () => string;
}

/**
 * Parses one document and writes its STXT-TREE-SPEC representation as JSON.
 *
 * @param args arguments after `describe`: exactly one file path, or `-` for the standard input.
 * @param io where to write canonical JSON and diagnostics.
 * @param deps injectable dependencies; see {@link DescribeDependencies}.
 * @returns `OK` on a successful syntactic parse, `FAILURE` for an unreadable or invalid document,
 *          and `USAGE` when the invocation is wrong.
 */
export function runDescribe(
    args: string[],
    io: CliIO,
    deps: DescribeDependencies = {}
): ExitCode {
    const file = parseArgs(args, io);
    if (file === null) {
        return ExitCode.USAGE;
    }

    const cwd = deps.cwd ?? process.cwd();
    const source: DocumentSource = file === STDIN_TARGET
        ? { name: STDIN_NAME, dir: cwd, read: deps.readStdin ?? readStdin }
        : fileSource(path.resolve(cwd, file));

    let content: string;
    try {
        content = source.read();
    } catch (error) {
        io.err(`${source.name}: cannot read (${(error as Error).message})`);
        return ExitCode.FAILURE;
    }

    const result = new Parser().parseResult(content);
    if (result.hasErrors()) {
        for (const error of result.getErrors()) {
            io.err(`${source.name}:${error.line}: [${error.code}] ${error.message}`);
        }
        return ExitCode.FAILURE;
    }

    io.out(toCanonicalJson(result.getNodes()));
    return ExitCode.OK;
}

/**
 * Validates the one positional argument accepted by `describe`.
 *
 * @param args arguments after `describe`.
 * @param io where to report usage errors.
 * @returns the source-file path (or `-`), or null when the invocation is invalid.
 */
function parseArgs(args: string[], io: CliIO): string | null {
    if (args.length === 0) {
        io.err("stxt describe: missing file");
        io.err("Usage: stxt describe <file|->");
        return null;
    }

    if (args.length > 1) {
        const option = args.find(arg => arg !== STDIN_TARGET && arg.startsWith("-"));
        if (option !== undefined) {
            io.err(`stxt describe: unknown option: ${option}`);
        } else {
            io.err("stxt describe: accepts exactly one file");
        }
        return null;
    }

    if (args[0] !== STDIN_TARGET && args[0].startsWith("-")) {
        io.err(`stxt describe: unknown option: ${args[0]}`);
        return null;
    }

    return args[0];
}
