/**
 * Implementation of `stxt describe <file|->`.
 *
 * This command deliberately parses only the base STXT grammar. A canonical tree describes the
 * parser result defined by STXT-TREE-SPEC; schema discovery and validation are a separate layer
 * and belong to `stxt validate`. On success, stdout contains precisely one canonical JSON document
 * generated by the public API of `@stxt-lang/core`. `-` reads the document from the standard
 * input, reported as `<stdin>` in the diagnostics.
 *
 * The parser limit flags (`--max-nesting`, `--max-line-length`, `--max-input-size`; see
 * LimitFlags.ts) raise, lower or disable (`-1`) the limits of STXT-SPEC §11.2 — e.g.
 * `--max-input-size -1` to emit the tree of a log file larger than the recommended default.
 */

import * as path from "path";
import { Parser, ParserOptions, toCanonicalJson } from "@stxt-lang/core";
import { CliIO } from "../runtime/Cli";
import { ExitCode } from "../runtime/ExitCode";
import { applyLimitFlag, isLimitFlag, LIMIT_FLAGS_USAGE } from "../runtime/LimitFlags";
import { linesOf } from "../runtime/LineReader";
import { DocumentSource, fileSource, readStdin, STDIN_NAME, STDIN_TARGET } from "../runtime/StxtFiles";

/** Dependencies {@link runDescribe} needs beyond argument parsing. */
export interface DescribeDependencies {
    /** Working directory relative paths are resolved against. Defaults to `process.cwd()`. */
    cwd?: string;

    /** How `-` reads the standard input. Defaults to reading the real one. */
    readStdin?: () => string;
}

/**
 * Parses one document and writes its STXT-TREE-SPEC representation as JSON.
 *
 * @param args arguments after `describe`: exactly one file path, or `-` for the standard input,
 *             plus the parser limit flags
 *             (`--max-nesting`/`--max-line-length`/`--max-input-size N`; `-1` disables one).
 * @param io where to write canonical JSON and diagnostics.
 * @param deps injectable dependencies; see {@link DescribeDependencies}.
 * @returns `OK` on a successful syntactic parse, `FAILURE` for an unreadable or invalid document,
 *          and `USAGE` when the invocation is wrong.
 */
export function runDescribe(
    args: string[],
    io: CliIO,
    deps: DescribeDependencies = {}
): ExitCode {
    const parsed = parseArgs(args, io);
    if (parsed === null) {
        return ExitCode.USAGE;
    }

    const cwd = deps.cwd ?? process.cwd();
    const stdin = deps.readStdin ?? readStdin;
    const source: DocumentSource = parsed.file === STDIN_TARGET
        ? { name: STDIN_NAME, dir: cwd, read: stdin, lines: () => linesOf(stdin()) }
        : fileSource(path.resolve(cwd, parsed.file));

    let content: string;
    try {
        content = source.read();
    } catch (error) {
        io.err(`${source.name}: cannot read (${(error as Error).message})`);
        return ExitCode.FAILURE;
    }

    const result = new Parser(parsed.limits).parseResult(content);
    if (result.hasErrors()) {
        for (const error of result.getErrors()) {
            io.err(`${source.name}:${error.line}: [${error.code}] ${error.message}`);
        }
        return ExitCode.FAILURE;
    }

    io.out(toCanonicalJson(result.getNodes()));
    return ExitCode.OK;
}

/** The result of successfully parsing the arguments of `describe`. */
interface ParsedArgs {
    file: string;
    limits: ParserOptions;
}

/**
 * Parses the arguments of `describe`: one positional argument plus the limit flags.
 *
 * @param args arguments after `describe`.
 * @param io where to report usage errors.
 * @returns the source-file path (or `-`) and the parser limits, or null when the invocation is
 *          invalid (already reported).
 */
function parseArgs(args: string[], io: CliIO): ParsedArgs | null {
    const paths: string[] = [];
    const limits: ParserOptions = {};

    for (let i = 0; i < args.length; i++) {
        const arg = args[i];

        if (isLimitFlag(arg)) {
            if (!applyLimitFlag(limits, arg, args[++i], "stxt describe", io)) {
                return null;
            }
        } else if (arg === STDIN_TARGET) {
            paths.push(arg);
        } else if (arg.startsWith("-")) {
            io.err(`stxt describe: unknown option: ${arg}`);
            return null;
        } else {
            paths.push(arg);
        }
    }

    if (paths.length === 0) {
        io.err("stxt describe: missing file");
        io.err(`Usage: stxt describe <file|-> ${LIMIT_FLAGS_USAGE}`);
        return null;
    }

    if (paths.length > 1) {
        io.err("stxt describe: accepts exactly one file");
        return null;
    }

    return { file: paths[0], limits };
}
